######## Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Tester",
    "password": "abcabc"
}

################################ Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "PhamHai",
    "password": "123456"
}

######## post Create new course
POST https://coursani.herokuapp.com/api/course/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTM0YzRmMGU4MGNhMzAwMDQ1ZDZhNTAiLCJpYXQiOjE2MzA4OTUyNDd9.Dp8YjlkWyK4MMF1uVBjJKk8Xpj4EEQu8a_9hZHkr6nY

{
    "title": "VueXXX ",
    "description": "Học VueX trong 1 video duy nhat",
    "url": "https://expressjs.com/"
}
######## get list course 
GET https://coursani.herokuapp.com/api/course/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

######## put edit course
PUT https://coursani.herokuapp.com/api/course/61346f709991ee0004bfa48e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

{
    "title": "Hoc NodeJS",
    "description": "Học NodeJS và Express và nhiều thứ linh tinh",
    "url": "https://expressjs.com/",
    "state": "DOING"
}
######## delete
DELETE https://coursani.herokuapp.com/api/course/611b8649d08ba736344f8f5xx
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk
